title: Основной заголовок сайта
email: your-email@example.com
description: Основное описание сайта
baseurl: "" # подпуть сайта, например. /blog
url: "" # базовое имя хоста и протокол сайта, например. http://example.com

# Подключение плагинов
plugins:
  - jekyll-feed

# Включение файлов и каталогов в сборку
include:
  - _pages

# Исключение файлов и каталогов из сборки
# Файлы и каталоги которые не попадут в каталог _site
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
