version: 0.0.16
title: Основной заголовок сайта
email: your-email@example.com
description: Основное описание сайта
url: "" # базовое имя хоста и протокол сайта, например. http://example.com
baseurl: "" # подпуть сайта, например. /blog
themecolor: '#ee1b24'
permalink: /blog/:name-:categories.html # https://jekyllrb.com/docs/permalinks/#built-in-formats

# export JEKYLL_ENV=production|development
google_analytics: UA-XXXXXXXXX-X
yandex_metrika: XXXXXX

# Подключение плагинов
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-inline-svg

# Поддержка scss стилей
sass:
  sass_dir: _scss
  style: compressed

# Подсветка синтаксиса
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Коллекции
collections:
  steps:
    output: true
    permalink: /:collection/:name.html
    order:
      - install.md
      - init.md

# Набор правил по умолчанию для создаваемых страниц через терминал
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      layout: base
      description:
      category:
      tags: []
      published: false
      sitemap: false
      excerpt_separator: <!--more-->
    posts:
      layout: base
      description:
      category:
      tags: []
      published: true
      sitemap: true
      excerpt_separator: <!--more-->
    steps:
      layout: base
      description:
      excerpt_separator: <!--more-->

# Пагинация
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Обрезка и изменение размера изображений
mini_magick:
  thumbnail:
    source: images/original
    destination: images/thumbnail
    resize: "530x390^"
    gravity: "center" # NorthWest, North, NorthEast, West, Center, East, SouthWest, South, SouthEast
    extent: "530x390"
  steps:
    source: images/original
    destination: images/steps
    resize: "550x450^"
    gravity: "center"
    extent: "550x450"

# Оптимизация изображений
svg:
  optimize: true
webp:
  enabled: true
  quality: 75
  img_dir: ['/assets/images/', '/images/']
  nested: true
  formats: ['.jpeg', '.jpg', '.png']
  regenerate: false
  exclude: ['icons']
  append_ext: true

# Включение файлов и каталогов в сборку
include:
  - _pages

# Исключение файлов и каталогов из сборки
# Файлы и каталоги которые не попадут в каталог _site
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
