version: 0.0.8
title: Основной заголовок сайта
email: your-email@example.com
description: Основное описание сайта
baseurl: "" # подпуть сайта, например. /blog
url: "" # базовое имя хоста и протокол сайта, например. http://example.com

# export JEKYLL_ENV=production|development
google_analytics: UA-XXXXXXXXX-X
yandex_metrika: XXXXXX

# Подключение плагинов
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Поддержка scss стилей
sass:
  sass_dir: _scss
  style: compressed

# Подсветка синтаксиса
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Коллекции
collections:
  recipe:
    output: true
    permalink: /:collection/:name-:i_day:i_month:short_year

# Набор правил по умолчанию для создаваемых страниц через терминал
jekyll_compose:
  auto_open: true
  default_front_matter:
    drafts:
      description:
      category:
      tags: []
      published: false
      sitemap: false
      excerpt_separator: <!--more-->
    posts:
      description:
      category:
      tags: []
      published: true
      sitemap: true
      excerpt_separator: <!--more-->
    recipe:
      layout: post
      description:
      excerpt_separator: <!--more-->

# Включение файлов и каталогов в сборку
include:
  - _pages

# Исключение файлов и каталогов из сборки
# Файлы и каталоги которые не попадут в каталог _site
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
